### ISSUE TITLE
The sample code does not work.

### ISSUE THREAD

**Issue by ksaegusa** [langchain-ai/langchain-aws#196]
Version: v2.0

The sample code provided in the repository's README.md does not work in version 2.0. 

```python
from langchain_aws import BedrockLLM

# Initialize the Bedrock LLM
llm = BedrockLLM(
    model_id="anthropic.claude-v2:1"
)

# Invoke the llm
response = llm.invoke("Hello! How are you today?")
print(response)
```
It seems there is an issue with the BedrockLLM class. 
This behavior appears to initialize `self.client` as `None`

```shell
Traceback (most recent call last):
  File "/home/ec2-user/environment/WORK/lib64/python3.9/site-packages/langchain_aws/llms/bedrock.py", line 727, in _prepare_input_and_invoke
    response = self.client.invoke_model(**request_options)
AttributeError: 'NoneType' object has no attribute 'invoke_model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/environment/be_ann.py", line 9, in <module>
    response = llm.invoke("Hello! How are you today?")
  File "/home/ec2-user/environment/WORK/lib64/python3.9/site-packages/langchain_core/language_models/llms.py", line 391, in invoke
    self.generate_prompt(
  File "/home/ec2-user/environment/WORK/lib64/python3.9/site-packages/langchain_core/language_models/llms.py", line 756, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/ec2-user/environment/WORK/lib64/python3.9/site-packages/langchain_core/language_models/llms.py", line 950, in generate
    output = self._generate_helper(
  File "/home/ec2-user/environment/WORK/lib64/python3.9/site-packages/langchain_core/language_models/llms.py", line 793, in _generate_helper
    raise e
  File "/home/ec2-user/environment/WORK/lib64/python3.9/site-packages/langchain_core/language_models/llms.py", line 780, in _generate_helper
    self._generate(
  File "/home/ec2-user/environment/WORK/lib64/python3.9/site-packages/langchain_core/language_models/llms.py", line 1514, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/home/ec2-user/environment/WORK/lib64/python3.9/site-packages/langchain_aws/llms/bedrock.py", line 1092, in _call
    text, tool_calls, llm_output = self._prepare_input_and_invoke(
  File "/home/ec2-user/environment/WORK/lib64/python3.9/site-packages/langchain_aws/llms/bedrock.py", line 738, in _prepare_input_and_invoke
    raise ValueError(f"Error raised by bedrock service: {e}")
ValueError: Error raised by bedrock service: 'NoneType' object has no attribute 'invoke_model'
```
