### ISSUE TITLE
ChatBedrockConverse doesn't support structured output with Bedrock Llama 3.3

### ISSUE THREAD

**Issue by tioans** [langchain-ai/langchain-aws#359]
### Description

I am trying to get `browser-use` to work with Llama 3.3 via Bedrock, but I get an error when trying to use structured output. Structured output is necessary to make the model work in this context. It seems the issue comes from the `with_structured_output` method, as I can execute calls without it, but in that case, the output is not correct.

### Error

"'RunnableSequence' object has no attribute 'with_structured_output'"

#### Structured output

```python
import asyncio
from dotenv import load_dotenv
from typing import Any, Dict, List

from pydantic import BaseModel, Field

from langchain_openai import AzureChatOpenAI
from langchain_ollama import ChatOllama
from langchain_aws import ChatBedrockConverse
from browser_use import Agent, Browser, BrowserConfig

class StructuredOutput(BaseModel):

    current_state: CurrentState = Field(
            description="Contains the current state details of the browser page."
        )
    
        action: List[Dict[str, Dict[str, Any]]] = Field(
            description=(
                "A list of actions to be executed in sequence. Each action should have one key "
                "that represents the action name and a value with the corresponding parameters."
            )
        )
 
```

#### Main method:

```python
async def main():

    llm = ChatBedrockConverse(
            model_id="meta.llama3-3-70b-instruct-v1:0",
            temperature=0,
            verbose=True
        )

    structured_llm = llm.with_structured_output(StructuredOutput, include_raw=False)

    agent = Agent(
        task="Search for the weather in Copenhagen and return the latest.",
        llm=structured_llm,
        validate_output=True
    )
    result = await agent.run()
    print(result)


if __name__ == "__main__":
    asyncio.run(main())

```

**Comment by Amitgb14** [comment]
@tioans Did you try meta.llama3.1 latest model, I think the old model not support this.

**Comment by tioans** [comment]
Turns out, `browser-use` already uses `.with_structured_output` in its calls, so adding it yourself is what triggers the error. The real issue of the Converse API not supporting output from models such as this is another discussion, so I think we can close this one.
